---
apiVersion: v1
kind: ConfigMap
metadata:
  name: k6-ratelimit-proto
  namespace: default
data:
  rls.proto: |
    syntax = "proto3";

    package envoy.service.ratelimit.v3;

    option go_package = "github.com/envoyproxy/go-control-plane/envoy/service/ratelimit/v3;ratelimitv3";

    // Rate limit request/response messages
    message RateLimitRequest {
      string domain = 1;
      repeated RateLimitDescriptor descriptors = 2;
      uint32 hits_addend = 3;
    }

    message RateLimitDescriptor {
      message Entry {
        string key = 1;
        string value = 2;
      }
      repeated Entry entries = 1;
      uint32 limit = 2;
    }

    message RateLimitResponse {
      enum Code {
        UNKNOWN = 0;
        OK = 1;
        OVER_LIMIT = 2;
      }

      message RateLimit {
        string name = 1;
        uint32 requests_per_unit = 2;
        Unit unit = 3;
        
        enum Unit {
          UNKNOWN = 0;
          SECOND = 1;
          MINUTE = 2;
          HOUR = 3;
          DAY = 4;
        }
      }

      message DescriptorStatus {
        Code code = 1;
        RateLimit current_limit = 2;
        uint32 limit_remaining = 3;
        uint64 duration_until_reset = 4;
      }

      Code overall_code = 1;
      repeated DescriptorStatus statuses = 2;
      repeated string request_headers_to_add = 3;
      map<string, string> raw_body = 4;
      map<string, string> dynamic_metadata = 5;
    }

    // The rate limit service definition
    service RateLimitService {
      rpc ShouldRateLimit(RateLimitRequest) returns (RateLimitResponse) {}
    }